services:
  portainer:
    image: 185.89.22.58:8082/repository/parseh-docker-private/portainer/portainer-ce:2.9.3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: unless-stopped
    container_name: portainer
