version: "3.7"

x-minio-common: &minio-common
  image: "185.89.22.58:8082/repository/parseh-docker-private/minio:latest"
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5
  restart: unless-stopped
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ../../pcmms/minio-data/data1-1:/data1
      - ../../pcmms/minio-data/data1-2:/data2
    networks:
      nginx_network:
        ipv4_address: ${network_ip_address1}
  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - ../../pcmms/minio-data/data2-1:/data1
      - ../../pcmms/minio-data/data2-2:/data2
    networks:
      nginx_network:
        ipv4_address: ${network_ip_address2}
  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - ../../pcmms/minio-data/data3-1:/data1
      - ../../pcmms/minio-data/data3-2:/data2
    networks:
      nginx_network:
        ipv4_address: ${network_ip_address3}
  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - ../../pcmms/minio-data/data4-1:/data1
      - ../../pcmms/minio-data/data4-2:/data2
    networks:
      nginx_network:
        ipv4_address: ${network_ip_address4}
networks:
  nginx_network:
    name: ${network_name}
    external: true