version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Tehran
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./snippets:/etc//nginx/snippets
      - ./ssl:/etc/nginx/ssl
      # - /etc/letsencrypt/live/sepehream.com/fullchain.pem:/etc/nginx/letsencrypt/live/sepehream.com/fullchain.pem
      # - /etc/letsencrypt/live/sepehream.com/privkey.pem:/etc/nginx/letsencrypt/live/sepehream.com/privkey.pem
    networks:
      main_nginx_network:
       ipv4_address: 172.30.10.1
    restart: always
networks:
  main_nginx_network:
    name: pcmms_proxy
    external: true